# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('content', models.TextField(max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.Comment')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('user_id', 'content_type', 'object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='comment',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
