# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([]),
        ),
    ]
